package model

import "time"

var Releases []Release = []Release{
	{
		Title:     "The many in few",
		Category:  "Thriller",
		Synopsis:  "A triller films about a large rebelious group of status quo",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "14456",
		Date:      time.Date(2024, time.November, 5, 0, 0, 0, 0, time.Local),
	},
	{
		Title:     "Mr. Silhouette",
		Category:  "Animation",
		Synopsis:  "An antholgy of mr silhouette and his pals, touch aspects of life from the past, present & the future.",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "34577",
		Date:      time.Date(2024, time.September, 15, 0, 0, 0, 0, time.Local),
	},
	{
		Title:     "Who won",
		Category:  "Comedy",
		Synopsis:  "A competition no one was playing but the participants expected a winner!",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "16010",
		Date:      time.Date(2025, time.January, 25, 0, 0, 0, 0, time.Local),
	},
	{
		Title:     "Automated!",
		Category:  "Science",
		Synopsis:  "A science & technology based filsm on the advances made those far & the expected advances to come.",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "40046",
		Date:      time.Date(2025, time.June, 17, 0, 0, 0, 0, time.Local),
	},
	{
		Title:     "Id 001",
		Category:  "Satire",
		Synopsis:  "Indetification, labelling, associations & more on differentiation of objects from each other",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "87006",
		Date:      time.Date(2024, time.December, 5, 0, 0, 0, 0, time.Local),
	},
	{
		Title:     "Not you",
		Category:  "Animation",
		Synopsis:  "explore the different perspectives of a single event. Trust me they are alot, some had to be dropped, some never viewed.",
		Thumbnail: "/public/thum.png",
		Trailer:   "/public/dribble.mp4",
		Url:       "/public/dribble.mp4",
		Id:        "31796",
		Date:      time.Date(2024, time.December, 28, 0, 0, 0, 0, time.Local),
	},
}

var Timelines []Timeline = []Timeline{
	{
		Title:    "The many in few",
		Category: "Thriller",
		Id:       "1503",
		Ref:      "14456",
		Date:     time.Date(2024, time.November, 5, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "Mr. Silhouette",
		Category: "Animation",
		Id:       "1504",
		Ref:      "34577",
		Date:     time.Date(2024, time.September, 15, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "Who won",
		Category: "Comedy",
		Id:       "1505",
		Ref:      "16010",
		Date:     time.Date(2025, time.January, 25, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "Automated!",
		Category: "Science",
		Id:       "1506",
		Ref:      "40046",
		Date:     time.Date(2025, time.June, 17, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "Id 001",
		Category: "Satire",
		Id:       "1507",
		Ref:      "87006",
		Date:     time.Date(2024, time.December, 5, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "Not you",
		Category: "Animation",
		Id:       "1508",
		Ref:      "31796",
		Date:     time.Date(2024, time.December, 28, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "A flash Bang!",
		Category: "Thriller",
		Id:       "1509",
		Ref:      "",
		Date:     time.Date(2025, time.October, 21, 0, 0, 0, 0, time.Local),
	},
	{
		Title:    "I do not, Do you?",
		Category: "Family",
		Id:       "1510",
		Ref:      "",
		Date:     time.Date(2025, time.December, 20, 0, 0, 0, 0, time.Local),
	},
}
